try {
    console.log(a)
}
catch (err) {
    console.log(err)
}

function test() {
    console.log("test sucessfull")
}
test()